### ISSUE TITLE
pandoc-sidenote 0.20.0 is not on Hackage

### ISSUE THREAD

**Issue by clinty** [jez/pandoc-sidenote#14]
Please upload to Hackage

**Comment by jez** [comment]
ooc whats the benefit to this being on hackage?

there are already binary releases in the downloads.

**Comment by clinty** [comment]
In Debian we have tooling based on Hackage and Stackage.  For example, we have a "package plan" which allows us to test if a set of packages are co-installable.  If the metadata aren't available on Hackage, this complicates things, though it's not impossible to work around.

**Comment by peti** [comment]
> ooc whats the benefit to this being on hackage?

NixOS has tools that automatically package all of Hackage. If this package isn't uploaded to Hackage, then we cannot distribute it easily.

**Comment by peti** [comment]
Ping?

**Comment by jez** [comment]
Honestly, I can't even find the log in button for hackage. If someone wants to take over maintenance of this package on hackage i'm happy to give someone the rights to do so, but I don't even know how to sign in so you'd have to tell me how to do that step by step

**Comment by p3palazzo** [comment]
Bummer. I’m trying to create a docker image with Jekyll, pandoc-jekyll, tufte-pandoc-jekyll and pandoc-sidenote. Is there any convenient way of getting the pandoc-sidenote bin on an alpine image without using cabal?

**Comment by cdepillabout** [comment]
@jez Most Haskellers expect the Haskell packages they use to be up on Hackage.  Its the "standard" place to distribute Haskell packages.

As peti and clinty said above, there are multiple Linux distributions that are able to automatically package and distribute Haskell packages on Hackage.

In order to upload a package to Hackage, you can use the upload page: https://hackage.haskell.org/upload.  That links to https://hackage.haskell.org/packages/upload.

I imagine this will ask you to login when you actually try to upload the package.

Alternatively, you can use the `stack upload .` command to upload a package with the Stack command-line tool.

-------------------------------

Nixpkgs has users (well, at least one user) that wants `pandoc-sidenote` available in Nixpkgs: https://github.com/NixOS/nixpkgs/pull/93421.  If releases of `pandoc-sidenote` were uploaded to Hackage, we could automatically package and distribute them in Nixpkgs.

**Comment by jez** [comment]
https://hackage.haskell.org/package/pandoc-sidenote-0.20.0.0

https://hackage.haskell.org/package/pandoc-sidenote-0.22.1.0
