### ISSUE TITLE
Please push 0.22 to homebrew

### ISSUE THREAD

**Issue by mkirchner** [jez/pandoc-sidenote#19]
Hi jez,

Thanks for fixing #15. Can you still push the 0.22 version to your homebrew tap, please?

Still getting this:
```
pandoc-sidenote (master*) $ brew upgrade pandoc-sidenote
Warning: jez/formulae/pandoc-sidenote 0.20.0 already installed
pandoc-sidenote (master*) $
```

Thanks!

**Comment by jez** [comment]
Hey, I tried for a few hours this afternoon getting it to work. I pushed something, but it doesn't work on my laptop. Maybe it will work on yours.

In any case, I usually install this from source on my machines, so I'm not that invested in publishing to Homebrew, especially because I use Linux half the time anyways.

If it doesn't work and you'd like, feel free to maintain your own tap, or submit a new formula upstream to Homebrew itself (the Homebrew team prefer non-authors submitting formulae anyway).

**Comment by mkirchner** [comment]
Hi @jez, thanks for putting in the time to try to get it to work. I am on macOS and the reason it's not working there is that the `pandoc-citeproc` executable is an ELF binary for a Linux system:

```
~ $ file /usr/local/Cellar/pandoc-sidenote/0.22.0/bin/pandoc-sidenote
/usr/local/Cellar/pandoc-sidenote/0.22.0/bin/pandoc-sidenote: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /home/linuxbrew/.linuxbrew/lib/ld.so, for GNU/Linux 3.2.0, stripped
```

That said, I understand your point and I'll dig into installing from source. Thanks again!

**Comment by jez** [comment]
that’s wild thanks for finding that!

i might be able to fix that i’ll let you know

**Comment by jez** [comment]
I believe it works now. You may have to delete any old zip files and also update the jez/formulae tap with `brew update`.

Thanks again!
