### ISSUE TITLE
Building against Pandoc 1.19

### ISSUE THREAD

**Issue by Bill-Costa** [jez/pandoc-sidenote#5]
Installed the latest Pandoc from binary package: 

> pandoc 1.19.2.1
> Compiled with pandoc-types 1.17.0.4, texmath 0.9, skylighting 0.1.1.4

Downloaded latest version of stack and GHC.  Downloaded panoc-sidenote and updated the 
stack.yaml to reflect the pandoc version:

> $ fgrep -i pandoc stack.yaml
> - pandoc-1.19
> - pandoc-types-1.17

Then:

> $ stack build
> Error: While constructing the build plan, the following exceptions were encountered:
> In the dependencies for pandoc-1.19:
>    texmath-0.8.6.7 must match >=0.9 && <0.10 (latest applicable is 0.9.3)
> needed due to pandoc-sidenote-0.9.0.0 -> pandoc-1.19
>
> Plan construction failed.

Using Mac OS X El Capitan (v10.11.6)

**Comment by jez** [comment]
Sorry for the delay. I have some spare time tonight, so hopefully I'll have an updated package out soon.

In case you want to try to beat me to it, I suspect you can just add

```
- texmath-0.9.1
```

to the `extra-deps` in `stack.yml`, and rebuild. I believe it's the same reason why `doctemplates-x.y.z` is in the `extra-deps`: neither package is in the default LTS resolver, so if we want to use newer versions (or build with packages that require newer versions) we need to tell Stack how to resolve the dependencies so that it can guarantee reproducible builds.

**Comment by jez** [comment]
I believe the newly released version [0.19.0](https://github.com/jez/pandoc-sidenote/releases/tag/0.19.0). It should also build cleanly if you're using Stack or Homebrew.

**Comment by Bill-Costa** [comment]
The building v0.19 works.  Thanks!
